encryption_key: "planetary"
topics: 
  - name: "/camera/color/image_raw/compressed"
    target_ips:
      - 192.168.122.1
  - name: "/camera/color/camera_info"
    target_ips:
      - 192.168.122.1
  - name: "/camera/imu"
    target_ips:
      - 192.168.122.1
port: 1234
send_frequency: 300
sender_queue_max_size: 5
hostname: "exomy"
